name: Flutter CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: quiz_app

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: Cache Flutter dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Decode and place google-services.json
      - name: Set up google-services.json
        run: |
          mkdir -p android/app
          echo "${GOOGLE_SERVICES_JSON}" > android/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      # Analyze the code
      - name: Analyze code
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test

      # (Optional) Build APK for Android
      - name: Build APK
        run: flutter build apk --release

      # (Optional) Build for iOS (only works on macOS runners)
      # - name: Build iOS
      #   if: runner.os == 'macOS'
      #   run: flutter build ios --no-codesign

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: quiz_app/build/app/outputs/flutter-apk/app-release.apk
